### ISSUE TITLE
panic: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/tfc-workflows-github#42]
If I use `hashicorp/tfc-workflows-github/actions/upload-configuration@v1.2.0` action with a workspace that doesn't exist in Terraform loud it panics.

```
error uploading configuration version to Terraform Cloud: resource not found
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type({0x0?, 0x0?, 0x[110](https://github.com/avaya/ccaas-iac-aiven/actions/runs/8202817401/job/22434371175#step:3:122)?})
	/usr/local/go/src/reflect/value.go:2453 +0x12e
github.com/hashicorp/tfci/internal/command.(*outputMessage).Value(0xc00014c1b0)
	/src/internal/command/output.go:39 +0xf9
github.com/hashicorp/tfci/internal/command.(*Meta).closeOutput(0xc00043c0a0)
	/src/internal/command/meta.go:121 +0x12b
github.com/hashicorp/tfci/internal/command.(*UploadConfigurationCommand).Run(0xc000434390, {0xc00001e0d0, 0x3, 0x3})
	/src/internal/command/upload.go:65 +0x64b
github.com/mitchellh/cli.(*CLI).Run(0xc0000b9a40)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5f8
main.realMain()
	/src/main.go:61 +0xf6
main.main()
	/src/main.go:46 +0x1b4
```

**Comment by FarhanSajid1** [comment]
Any workarounds for this? Seeing this for a workspace that does exist

**Comment by fs-david-harrington** [comment]
I just started to have the exact same issue; affecting all workspaces, that use hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
workspace exist, token is not expired.

**Comment by eduardobellido-st** [comment]
~~Same problem here.~~

Edit:

After some troubleshooting, we realized that the team token used didn't have permissions to access the target workspace.
